### ISSUE TITLE
안드로이드 피드생성 요청시 500에러

### ISSUE THREAD

**Issue by Glacier-Han** [GDSC-KNU/4CutAlbum-server#22]
현재 피드생성 화면 제작중입니다.

base64 인코딩 후
친구, 스튜디오, 코멘트, 인원수, 해시태그 이렇게 입력 후 전송하면 500에러가 납니다.

특정 경우 (친구와 해시태그 제외하고 입력함)에 정상적으로 전송되면서 s3 사진링크가 리스폰스로 들어옵니다.
하지만 전체보기 조회해도 나오지 않습니다.
추가로 해시태그 조회시에는 ("test1", "test2") 처럼 쉼표로 구분된 스트링 파라미터가 들어가는데
피드 생성시에는 단순히 string[]라고 표기되어있어 어떤 형식으로 보내야하는지 식별이 힘듭니다.

가능하시면 포스트맨으로 피드생성 예시 리퀘스트, 리스폰스를 캡쳐해주시면 개발하는데 도움이 될듯 합니다.
@Int-TRUE

**Comment by chaejm55** [comment]
혹시 전체보기 조회가 안 된다는게 저번처럼 access denied가 뜬다는 말씀이신가요?

**Comment by Glacier-Han** [comment]
아뇨 s3문제는 아닌거같고 db에 안들어가거나, 조회가 안되는 것 같습니다

**Comment by sami355-24** [comment]
Q.친구, 스튜디오, 코멘트, 인원수, 해시태그 이렇게 입력 후 전송하면 500에러가 납니다.
A. 500에러는 ec2가 갑자기 먹통이 돼서 생긴듯 합니다. 현재 조치 해놓았습니다.

Q.특정 경우 (친구와 해시태그 제외하고 입력함)에 정상적으로 전송되면서 s3 사진링크가 리스폰스로 들어옵니다.
하지만 전체보기 조회해도 나오지 않습니다.
A. "친구"가 어떤것을 말씀하시는지 모르겠습니다. 현재 피드 생성 api는 노션이 있는 api명세서를 따르고 있습니다. 추가로 현재 해시태그를 선택하지 않고 피드생성 요청을 보낼시 피드생성은 되나 조회시 해시태그 없이 생성한 피드는 조회가 안됩니다. 추후에 해시태그값을 빈값으로 넘길시 에러처리하도록 조치하겠습니다.

Q.추가로 해시태그 조회시에는 ("test1", "test2") 처럼 쉼표로 구분된 스트링 파라미터가 들어가는데
피드 생성시에는 단순히 string[]라고 표기되어있어 어떤 형식으로 보내야하는지 식별이 힘듭니다.
가능하시면 포스트맨으로 피드생성 예시 리퀘스트, 리스폰스를 캡쳐해주시면 개발하는데 도움이 될듯 합니다.
A. 노션에 피드생성 바디값을 올려놓도록 하겠습니다.
