### ISSUE TITLE
안드로이드 피드생성 500 error

### ISSUE THREAD

**Issue by Glacier-Han** [GDSC-KNU/4CutAlbum-server#25]
<img width="1627" alt="image" src="https://github.com/GDSC-KNU/4CutAlbum-server/assets/61905052/14c5835a-77b8-4df3-b76e-e85bac4adb44">

이렇게 각 데이터들이 잘 들어가는 것 같은데도 500에러가 뜨네요ㅜ
UID나 BASE64 String 길이가 너무 길어서 그럴까요? 
@sami355-24

**Comment by sami355-24** [comment]
해시태그는 DB에 있는 값으로만 생성 요청을 해야만 정상처리가 됩니다.
